version: '3.1'

services:

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  be:
    build:
      context: ./tracker-be
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./tracker-be:/var/www/tracker-be
      - /var/www/tracker-be/node_modules
    environment:
      MONGO_URL: mongodb
    depends_on:
      - mongodb

volumes:
  mongodb-data:
    name: mongodb-data
